### ISSUE TITLE
删除子项的时候触发验证

### ISSUE THREAD

**Issue by wapco** [SeriaWei/ZKEACMS#280]
![tim 20190220144629](https://user-images.githubusercontent.com/29369553/53071833-5140c100-351e-11e9-94ad-7baab60f0761.png)

如上图显示

**Comment by SeriaWei** [comment]
目前仅处理了必填问题。
在这里触发验证是因为有后端验证。

1. 已添加的数据在删除时还是需要提交回后端，后端有验证机制，如果数据验证不过则通过不了。
2. 对于新加的数据是可以做到不验证的。但这要求要删除时，重新排form input的索引。

所以这里统一用户体验，对输入值进行验证。
