### ISSUE TITLE
Does zkeacms support oauth authentication which is defined by ourselves?

### ISSUE THREAD

**Issue by linxiaolicnic** [SeriaWei/ZKEACMS#289]
Does zkeacms support oauth authentication which is defined by ourselves?

**Comment by SeriaWei** [comment]
Yes, of course. You can develop a plug-in to do this. This is almost the same as being implemented in ASP. NET Core.
Actually, we have 'ZKEACMS.OAuth' plug-in in Enterprise edition.

**Comment by linxiaolicnic** [comment]
Is this ZKEACMS.OAuth http://www.zkea.net/zkeacms/extend/detail/post-155.html?
But it says just support QQ，微博，微信登录，后续会增加支持更多第三方账号。
我们有自己的oauth通行证系统，如果购买企业版可以支持吗?

**Comment by SeriaWei** [comment]
嗯，是的我们实现的是公用的OAuth登录。您购买企业版后，可以添加或者修改成你们自己的OAuth通行系统

**Comment by linxiaolicnic** [comment]
如果用开源版，我们能自己修改oauth通行证吗？

**Comment by SeriaWei** [comment]
可以的，你们自己的oauth通行证系统，接入始终是要你们自己写的。
