### ISSUE TITLE
产品或者是新闻的子分类无法调取

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#296]
![image](https://user-images.githubusercontent.com/36066258/56723318-48b57280-677b-11e9-9411-4a6748aa2826.png)
产品和新闻一样，没有办法调取产品的子类的分类

**Comment by SeriaWei** [comment]
目前文章类别和产品类别组件的处理逻辑是一样的。即只获取所选类别的**一级子类别**，如果你需要获取所有子类别，可修改相关代码

### 文章组件
https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.Article/Service/ArticleTypeWidgetService.cs#L44

### 产品组件
https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.Product/Service/ProductCategoryWidgetService.cs#L68
