### ISSUE TITLE
在自定义内容详情页没有办法填写关键词等信息

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#299]
http://demo.zkea.net/cn/shop/detail/post-11.html  根据官网的例子

**Comment by SeriaWei** [comment]
**请详细说明您遇到的问题！**
关于自定义内容从列表页面到详细页面可以参考下列文档：
> http://www.zkea.net/codesnippet/detail/post-101.html

**Comment by Nickyuyuyong** [comment]
自定义页面没有办法也SEO优化的关键词和描述等；

**Comment by SeriaWei** [comment]
已添加刚功能，在开发分支
