### ISSUE TITLE
在其他页面调用分类的时候分类链接有问题

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#300]
比如我在新闻页面想调用产品分类，这个时候调用出来的产品分类的链接就会有问题；

**Comment by SeriaWei** [comment]
目前产品分类和文章分类组件都以当前页面地址为基础来生成类别链接，从而影响页面中的列表数据。
我们会在后续版本中加入**列表页面**字段，允许用户指定特定的列表页面。

**Comment by SeriaWei** [comment]
这个可以在在线编辑模板的时候，在模板中使用正确的类别地址进行拼接即可。无需修改功能即可达到目的。
