### ISSUE TITLE
编辑页面没有办法编辑产品组件的代码

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#308]
比如在新闻列表页面编辑页面，然后对新闻列表组件模板进行编辑的时候，是显示空白
![image](https://user-images.githubusercontent.com/36066258/58863175-dd00e680-86e4-11e9-8e59-19154733ecfe.png)
![image](https://user-images.githubusercontent.com/36066258/58863128-c5296280-86e4-11e9-8188-ce9bc229eafa.png)

**Comment by SeriaWei** [comment]
可编辑的模板需要在系统中有预设。新添加的模板，需要做一个Fluid模板并添加到以下目录：
```
ZKEACMS.Fluid\Liquid
```

**Comment by Nickyuyuyong** [comment]
> 可编辑的模板需要在系统中有预设。新添加的模板，需要做一个Fluid模板并添加到以下目录：
> 
> ```
> ZKEACMS.Fluid\Liquid
> ```
这个是模板是要重新写，还是说又快捷的方法可以直接生成，我看这两个模板的语法有点不一样；

**Comment by SeriaWei** [comment]
没有。模板语法请参阅这里 http://www.zkea.net/codesnippet/detail/zkeacms-fluid-syntax.html
