### ISSUE TITLE
SEo优化模板没有对应的分类页面（产品分类，文章分类）

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#311]
![image](https://user-images.githubusercontent.com/36066258/59427941-77140d80-8e0e-11e9-8256-493f658e3299.png)
这里没有办法更新产品分类，文章分类的SEO

**Comment by SeriaWei** [comment]
同类别在不同页面的SEO信息其实都是一样的，所以直接到类别处维护即可。
