### ISSUE TITLE
复制功能的BUG

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#312]
复制功能，复制了产品直接修改内容和url 直接点击发布，就会出现这么一个问题，原来的数据被改了，必须要复制之后修改内容保存，然后在发布，，这样有点繁琐

**Comment by SeriaWei** [comment]
已修正，拉取合并最新代码即可。

**Comment by Nickyuyuyong** [comment]
现在官网的demo代码已经更新了改功能吗？好像测试还是不可以，另外复制功能还有个bug就是展示图这些是不能复制的

**Comment by SeriaWei** [comment]
demo站点没更新

**Comment by Nickyuyuyong** [comment]
还是有BUG,首先如过复制直接点击发布，会出现以下问题：展示图就不会保存发布到；

**Comment by SeriaWei** [comment]
感谢反馈，这个BUG将会包含在下个Release里面

**Comment by SeriaWei** [comment]
代码已提交到开发分支，如需要请自行合并
**注意：开发分支基于.net core 3.0 preview 6**
