### ISSUE TITLE
多语言的BUG

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#313]
多语言的BUG,在多语言的情况下，如过同一片新闻，URL不一样，那么sitemap就应该有多个sitemap,现在的就只有一个sitemap,robots也是同样道理

**Comment by SeriaWei** [comment]
## sitemap和robots都只有一个

当使用单域名的多语言模式时，`~/sitemap.xml`会包含创建的所有语言的Url
![image](https://user-images.githubusercontent.com/6006218/59691878-5b49a680-9216-11e9-841c-92dade56a3f9.png)

独立域名模式，只会列出当前域名对应语言的Url

robots没必要不同语言都设置一个不一样的
