### ISSUE TITLE
Sitemap的BUG

### ISSUE THREAD

**Issue by Nickyuyuyong** [SeriaWei/ZKEACMS#314]
自定义内容里面的列表页和详情页的页面在sitemap里面都没有，而且还有BUg就是一般我们会用做detail（文章，详情等）作为详情页的模板页，这个不应该出现在sitemap里面

**Comment by SeriaWei** [comment]
### 自定义内容
自定义内容的列表页面是会出现在sitemap里面的，详细页面没有，因为URL不好确定

### 产品、文章详细页
文章和产品的detail不会出现在sitemap里面，这个有排除，可以看下列代码
https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.Sitemap/Service/SiteUrlProviders/PageSiteUrlProvider.cs#L29
