### ISSUE TITLE
添加产品，文章或者是自定义内容等；保存或者是发布之后还是停留在编辑页面

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#317]
1：添加产品，文章或者是自定义内容等；保存或者是发布之后还是停留在编辑页面，应该发布，保存之后直接跳转到对应的列表页面
2：在自定义内容的种新增加了多种自定义内容类型，在其中一个自定义内容类型里面增加了数据，后点击取消，返回的列表页面不是改内容类型的列表；

**Comment by SeriaWei** [comment]
可以增加一个保存并退出

**Comment by SeriaWei** [comment]
Save and Exit commit:
7556098d3825f66ce34be6786cbabf05a9cbc6c9
6892070173eafc4a90305ab41f4f5f6324fdfb0c
