### ISSUE TITLE
用vue实现拖拽布局

### ISSUE THREAD

**Issue by hiwjcn** [SeriaWei/ZKEACMS#320]
用vue实现拖拽布局

**Comment by SeriaWei** [comment]
我们目前没有使用VUE重写拖拽布局的计划。在布局拖拽方面，我们目前使用的是jQuery UI 的`Draggable`，`Droppable`，`Sortable` 
https://jqueryui.com/

**Comment by hiwjcn** [comment]
谢谢解答
