### ISSUE TITLE
更新到正式版本的net core 3.0

### ISSUE THREAD

**Issue by ghd258** [SeriaWei/ZKEACMS#335]
更新到正式版本的net core 3.0

**Comment by SeriaWei** [comment]
最新的Code已经可以使用正式版的.net core 3.0了

**Comment by ghd258** [comment]
里面部分项目还用的是 Version="3.0.0-preview7.19365.7"

**Comment by ghd258** [comment]
@SeriaWei  3.0正式版都发布了 ，但是你们的里面还是3.0.0-preview7.19365.7

**Comment by SeriaWei** [comment]
@ghd258 更新已提交到develop分支，你可以更新试试看。
