### ISSUE TITLE
使用sqlite数据库出现错误提示：SQLite Error 14: 'unable to open database file'.

### ISSUE THREAD

**Issue by lygwys** [SeriaWei/ZKEACMS#337]
已经在wwwroot目录下建立了数据库wwwroot/App_Data/Database.sqlite
使用"MsSql"正常，但当改为"Sqlite"时提示如下错误：
Microsoft.Data.Sqlite.SqliteException:“SQLite Error 14: 'unable to open database file'.”

**Comment by SeriaWei** [comment]
`App_Data`目录应与`wwwroot`在相同目录下。
```
/App_Data/Database.sqlite
/wwwroot/...
```
