### ISSUE TITLE
vs2019运行源码报错

### ISSUE THREAD

**Issue by viproommimi** [SeriaWei/ZKEACMS#341]
显示少文件，直接f5与ctrl+f5均跑不起
![批注 2019-11-23 123730_LI](https://user-images.githubusercontent.com/52340229/69473309-5c4ab980-0dee-11ea-9c4f-d8bd6143c552.jpg)

**Comment by SeriaWei** [comment]
需要重新生成一下整个解决方案
http://www.zkea.net/zkeacms/document/startdev

**Comment by SeriaWei** [comment]
按 F6 或者 ctrl + shift + b 进行整个解决方案的生成

**Comment by viproommimi** [comment]
新手，感谢指导，这样操作后页面可以打开了，但是vs里面还提示有问题
![批注 2019-11-23 135534](https://user-images.githubusercontent.com/52340229/69474208-24953f00-0df9-11ea-968b-864b71f47ba2.png)
发出提示的是assemblyLoader.cs这个文件

**Comment by SeriaWei** [comment]
什么问题？

**Comment by viproommimi** [comment]
还是提示缺少aticle.dll那个文件，当然网页是跑起来了，只是vs里面有个这个红叉提示

**Comment by SeriaWei** [comment]
整个解决方案都有生成的话是不会有这个提示的。
