### ISSUE TITLE
个人觉得应该把主页很多css提取到一个文件中。

### ISSUE THREAD

**Issue by bbhxwl** [SeriaWei/ZKEACMS#350]
个人觉得应该把主页很多css提取到一个文件中。
我看有很多类似这样的代码

style="color: #ffffff; background-image: url('/UpLoad/Images/201905/6c82d4bdc4e94a59add2e43614bfc771.jpg'); background-size: cover; clip-path: polygon(0 0,100% 0,100% 82%,50% 100%,0 82%);"

**Comment by SeriaWei** [comment]
CMS的整体样式都在主题样式里面`Theme.css`，你可以查看[主题样式](https://www.zkea.net/zkeacms/document/theme)来了解更多。

你看到的这内联样式是在线编辑样式时生成的
### 在线编辑样式的相关文档和视频演示

- https://www.zkea.net/zkeacms/document/edit-style
- https://www.zkea.net/zkeacms/videos/view/edit-style.html
- https://v.vuevideo.net/share/post/5481323210292563522

希望能对你有帮助 :)
