### ISSUE TITLE
双层自定义模板嵌套，内层数据提交有问题

### ISSUE THREAD

**Issue by zhaobinbin2019** [SeriaWei/ZKEACMS#354]
自定义的list里面嵌套再嵌套一个自定义list,赋值的时候数据会错乱

**Comment by SeriaWei** [comment]
代码已经提交到develop分支了，可以更新再试试看

**Comment by zhaobinbin2019** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wayne"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 下午4:14
收件人: "SeriaWei/ZKEACMS"<ZKEACMS@noreply.github.com&gt;; 
抄送: "星云·风（宾宾）"<980433875@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SeriaWei/ZKEACMS] 双层自定义模板嵌套，内层数据提交有问题 (#354)




代码已经提交到develop分支了，可以更新再试试看
