### ISSUE TITLE
文章编辑中的换行功能如何实现？

### ISSUE THREAD

**Issue by qingwatianya** [SeriaWei/ZKEACMS#361]
1、文章编辑的时候 回车换行 看源代码 是：<p></p> 显示的时候  起不到<br/>的换行作用 ；
2、如果回车+空格 对应的源代码是：<p>&nbsp;</p> 能换行 但是换出来的行比起<br/>要高一些   看着间距太大又有点儿别扭；
3、 走数据库表 把<p></p>标签对换成<br/> 前端编辑加载数据的时候 又会还原成<p></p>  有点儿搞人呀！

**Comment by SeriaWei** [comment]
没太明白您的意思，信息好像没显示全！
直接**回车**是新的段落，段落之间是有间距的：
```
<p></p>
```
`shift`+`enter`是换行：
```
<br/>
```
您还可以不使用段落，使用div，这样是没有间距的
![image](https://user-images.githubusercontent.com/6006218/76145507-f0ead600-60c4-11ea-9bc5-019aff31d92e.png)

**Comment by qingwatianya** [comment]
感谢感谢 刚才问题留言里面的 <p\>和<br/\> 被直接当做代码给解析了 所以看起来乱七八糟的，我想要的就是 shift+enter是 谢谢🙏
