### ISSUE TITLE
点击保存布局时报错（500），且之前设计好的页面都没有了

### ISSUE THREAD

**Issue by AL18834408503** [SeriaWei/ZKEACMS#365]
![03234d65415b914930b9f40d1e234e7](https://user-images.githubusercontent.com/42667184/79297382-896c4580-7f10-11ea-838f-e4711b4514bb.png)
之后报500，且我原先设计好的页面都没有了，

**Comment by SeriaWei** [comment]
我试了保存布局没有问题，你是在什么情况下保存报错？

**Comment by AL18834408503** [comment]
[2020-04-15.log](https://github.com/SeriaWei/ZKEACMS/files/4480351/2020-04-15.log)

**Comment by SeriaWei** [comment]
应该是你的数据库初始化有问题，`LayoutHtmlId`是自增主键` INT AUTO_INCREMENT  NOT NULL`
```
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Field 'LayoutHtmlId' doesn't have a default value
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Field 'LayoutHtmlId' doesn't have a default value
```
这是相关表的那表脚本：
```
CREATE TABLE `CMS_LayoutHtml` (
	`LayoutHtmlId` INT AUTO_INCREMENT  NOT NULL,
	`LayoutId` VARCHAR(100) CHARACTER SET utf8mb4  NOT NULL,
	`PageId` VARCHAR(100) CHARACTER SET utf8mb4  NULL,
	`Html` LONGTEXT CHARACTER SET utf8mb4  NULL,
	......
);
```
初始化数据库你可以参考这个：http://www.zkea.net/codesnippet/detail/zkeacms-mysql.html

发布程序请参考这个文档：http://www.zkea.net/zkeacms/document/publish

### 文档中心
http://www.zkea.net/zkeacms/document
