### ISSUE TITLE
建议datatable添加多选删除操作

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#366]
一般在用模板建站之后内容基本都要修改，重新录入，那么如果模板站中的数据多的情况下，复制模板建站之后需要花费大量的人工去一条一条删除数据，非常糟糕

**Comment by SeriaWei** [comment]
![image](https://user-images.githubusercontent.com/6006218/87850870-08b15100-c926-11ea-96e1-e34c8a43b09c.png)
