### ISSUE TITLE
希望可以新增加一个数据库管理插件

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#378]
当站群的站点多了的时候，新增加了一个模板的时候，需要批量更新到所有站点，默认现在是手动更新到每个站的数据库中，很不方便，增加一个数据库管理插件，可以支持批量勾选多个数据库，然后同时执行某条sql语句

**Comment by SeriaWei** [comment]
[ZKEACMS.Updater](https://github.com/SeriaWei/ZKEACMS/tree/master/src/ZKEACMS.Updater) 插件用于在程序启动时执行数据库脚本更新数据库。
