### ISSUE TITLE
数据库创建批处理无法正常使用

### ISSUE THREAD

**Issue by anan121309** [SeriaWei/ZKEACMS#382]
见鬼了,你们难道没有做测试吗?如果是我个人的问题,难道不应该弄个文档指明一步步怎么做吗?数据库批处理命令运行时各种报错.怎么着都不行.数据库无法创建我没办法运行程序.

**Comment by SeriaWei** [comment]
报什么错？
创建数据库可以看这个文档  
http://www.zkea.net/zkeacms/document/createdatabase

**Comment by SeriaWei** [comment]
您的问题是否已解决？
