### ISSUE TITLE
提交自定义表单后邮件未发送并且程重启失败

### ISSUE THREAD

**Issue by SeriaWei** [SeriaWei/ZKEACMS#449]
![QQ图片20220105220728](https://user-images.githubusercontent.com/6006218/148236165-3b3c5783-51a9-45d4-af2c-949a136f800d.png)

**Comment by Timynore** [comment]
我已经收到了您的邮件，如果您还有其它事宜，欢迎您访问我的网站与我取得更多联系 www.zkea.net

**Comment by SeriaWei** [comment]
临时解决办法：手动删除`./wwwroot/Plugins/ZKEACMS.Mail`目录下的 Data.db，Data-log.db 两个文件
