### ISSUE TITLE
如何在自定义内容中的显示模板里面调用表单对应字段的模板

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#454]
![image](https://user-images.githubusercontent.com/36066258/160339069-3f2c3081-b4c8-447a-ab9d-1e7e028aaefd.png)
我在自定义列表板块里面增加了可以选择所需要的表单，但是在显示模板中不知如何调用循环输出表单的每个字段。
![image](https://user-images.githubusercontent.com/36066258/160339280-0398e3ca-0aaa-4992-a6aa-933d2f6f11bd.png)
求助大佬！

**Comment by SeriaWei** [comment]
在Service里面将表单的字段信息取出，然后放到ViewModel里面，传到View循环就可以了。
取表单信息参考 [FormWidgetService.cs](https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.FormGenerator/Service/FormWidgetService.cs)
循环显示字段参考 [Widget.Form.cshtml](https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.FormGenerator/Views/Widget.Form.cshtml)

**Comment by James0912KK** [comment]
好的，明白了，多谢
