### ISSUE TITLE
Form验证码Bug，提交错误的验证码时出现异常信息页面

### ISSUE THREAD

**Issue by w805756054** [SeriaWei/ZKEACMS#456]
![QQ拼音截图20220402234530](https://user-images.githubusercontent.com/14989628/161437076-20cdfd7f-963e-4139-9f20-63b6d52c1980.png)

**Comment by SeriaWei** [comment]
我们有重现这个问题，但错误信息跟你提供的不一样，不确定是不是同一个问题。能提供重现步骤吗？
