### ISSUE TITLE
页面默认引入了不必要的css和js

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#458]
页面默认引入了不必要的css和js怎么去掉，例如：
![image](https://user-images.githubusercontent.com/36066258/162930138-601e5ad4-751e-4ef7-98f2-320fcde22253.png)

**Comment by James0912KK** [comment]
好的。明白。另外我想请问一下
![image](https://user-images.githubusercontent.com/36066258/163505597-c8fcb864-f18e-485a-9ee5-ecca5f10eeb5.png)
在liquid语法中
{% style 'comments' %}
{% script 'comments' %}
这种都是只能显示在底部吗？怎么可以让她显示在顶部呢？或者让它显示在当前引入的位置呢？

**Comment by James0912KK** [comment]
最好是可以显示在所引入的位置，不然会出现CSS的优先级的问题；

**Comment by SeriaWei** [comment]
目前最新版本默认CSS是在顶部，JS是在底部。
