### ISSUE TITLE
cms后台多个功能点xss漏洞（CMS backend multiple function point XSS holes）

### ISSUE THREAD

**Issue by AnotherVol** [SeriaWei/ZKEACMS#459]
### 1.The background multiple function point XSS holes
1）产品类别 Product category
添加产品类别处 Add product categories
![添加产品类别](https://user-images.githubusercontent.com/13464049/163539345-3c386dc4-c9a1-4b3f-9884-29abeeae19cb.png)
保存后 After the save
![产品类别](https://user-images.githubusercontent.com/13464049/163539477-a1f47eac-e750-48a3-b789-c4a8164c079f.png)
2）文章类别 Category
![文章类别xss ](https://user-images.githubusercontent.com/13464049/163539597-7b58d4da-31d2-4b07-b499-3552c20cf96e.png)
保存后
![文章类别xss 1](https://user-images.githubusercontent.com/13464049/163539605-b252affc-5179-48a4-819a-74b5fb746a38.png)
3）在线客服和访客代码处
3) online customer service and visitors in the code
![访客代码](https://user-images.githubusercontent.com/13464049/163539749-0ad4e02b-0862-4b13-b034-9dd5e7b945db.png)
![访客代码](https://user-images.githubusercontent.com/13464049/163539757-bff35a3f-047d-486a-b534-3a865ab8ab42.png)
![2](https://user-images.githubusercontent.com/13464049/163539768-b6f30283-9aa8-4a9c-b137-791a0a2f8952.png)
![1](https://user-images.githubusercontent.com/13464049/163539772-6eeed9f0-a33f-48c4-ac46-50d9f1bac267.png)
### 2.修复建议 Repair advice
1.建议对后台用户输入进行控制。
1. The Suggestions to control the background user input.

**Comment by SeriaWei** [comment]
在线客服和统计代码本就是Javascript
