### ISSUE TITLE
开启多语言后访问页面无限重定向

### ISSUE THREAD

**Issue by SeriaWei** [SeriaWei/ZKEACMS#465]

**Comment by honeyyyyyy** [comment]
我也遇到这个问题，网站直接炸了。。。  admin都进不去

**Comment by Timynore** [comment]
我已经收到了您的邮件，如果您还有其它事宜，欢迎您访问我的网站与我取得更多联系 www.zkea.net

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by SeriaWei** [comment]
是的，是存在这个问题，我们今天会发布新版本修复这个问题。

**Comment by SeriaWei** [comment]
新版本已经发布了，更新后再试一下。

http://www.zkea.net/download

注意不要覆盖数据库。
