### ISSUE TITLE
推荐更换一个雪花算法

### ISSUE THREAD

**Issue by yitter** [SeriaWei/ZKEACMS#470]
比现在集成的雪花算法更好，链接：https://github.com/yitter/IdGenerator

**Comment by Timynore** [comment]
我已经收到了您的邮件，如果您还有其它事宜，欢迎您访问我的网站与我取得更多联系 www.zkea.net

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。
