### ISSUE TITLE
如何支持m3u8格式的视频播放呢？

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#480]
如何支持m3u8格式的视频播放呢？

**Comment by SeriaWei** [comment]
HTML 的video标签仅支持 MP4, WebM, and OGG 三咱视频格式。

**Comment by James0912KK** [comment]
我知道，现在发现客户在后台上传的视频都有几十兆甚至上百兆，播放起来很卡，加载很久。想说用m3u8。https://m3u8play.com/?play=https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 和这一样的

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by SeriaWei** [comment]
改一下`UseStaticFiles()`方法，把m3u8加进去：
```
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".m3u8"] = "application/x-mpegURL";
app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider
});
```

**Comment by James0912KK** [comment]
如何在上传mp4视频的时候自动转码成m3u8格式和ts格式的？
