### ISSUE TITLE
l请教一下iquid的模板中如何调用指定的方法

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#492]
比如：
![image](https://github.com/SeriaWei/ZKEACMS/assets/36066258/370300a7-4063-4751-a399-9f009749f7b8)
Url.ViewImageUrl，Url.GetHost，Url.PostUrl 这三个方法，如何在liquid模板中调用呢？

**Comment by SeriaWei** [comment]
不能直接调用，需要另外写对应的tag来达到相同的效果

**Comment by James0912KK** [comment]
请问再哪里写对应的tag?

**Comment by James0912KK** [comment]
好的，非常感谢！
