### ISSUE TITLE
Buy function

### ISSUE THREAD

**Issue by belhauge** [SeriaWei/ZKEACMS#494]
It would only be great if you only buy your enterprise version source code without having to use WeChat or QQ as this is not normal here in Europe and therefore difficult to access..

**Comment by SeriaWei** [comment]
After purchasing the enterprise version, you will receive the complete code, so you can easily disalbe QQ/WeChat widget or remove the code. We can also help you remove the relevant code, if you want to.

**Comment by belhauge** [comment]
I want to buy the enterprise version source code but I don't have anyone who has wechat so I can't be approved.

**Comment by SeriaWei** [comment]
We can communicate via email and conduct transactions through PayPal.

That's how we do business everywhere outside of China.

Email: seriawei@outlook.com

**Comment by belhauge** [comment]
Hallo

 

I am looking for the version where I can have several websites on the system, and have several customers who can have their own website..

 

What is price?

 

Beste Request 

Kim Belhauge

 

 

 

 

Fra: Wayne ***@***.***> 
Sendt: 19. august 2023 05:32
Til: SeriaWei/ZKEACMS ***@***.***>
Cc: belhauge ***@***.***>; Author ***@***.***>
Emne: Re: [SeriaWei/ZKEACMS] Buy function (Issue #494)

 

We can communicate via email and conduct transactions through PayPal.

That's how we do business everywhere outside of China.

Email: ***@***.*** ***@***.***>

**Comment by SeriaWei** [comment]
It's `Multi-tenant solution`, you can test this on our demo site: http://build.zkeasoft.com/account , sign up with an email and then you can create any websites.

# Price

| Edition | Price |
|:-------------|:-------------:|
| Enterprise |   **$1499.00USD**    |
| Multi-tenant solution | **$2299.00USD** |
