### ISSUE TITLE
现在新版本这个字段为什么不是之前那种拖拉形式呢？这种写起来很麻烦，容易出错

### ISSUE THREAD

**Issue by James0912KK** [SeriaWei/ZKEACMS#495]
![image](https://github.com/SeriaWei/ZKEACMS/assets/36066258/c4d2be6a-7674-4f99-bf33-b191ae2dd47c)

**Comment by SeriaWei** [comment]
这个功能重构过了，使用这个功能的一般都是开发人员，所以没做UI功能。
