### ISSUE TITLE
New query tag to include data in template

### ISSUE THREAD

**Issue by SeriaWei** [SeriaWei/ZKEACMS#510]
Query products
``` liquid
{% query %}
select prods from products where ID>0 skip 1 take 1 orderby ID desc
{% endquery %}
```
Display products
``` liquid
{% for item in prods %}
<p>{{item.Title}}</p>
{% endfor %}
```

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by SeriaWei** [comment]
Available datasource:

- Carousels
- Cultures
- Navigations
- ArticleGalleries
- Articles
- ArticleTypes
- Comments
- ProductCategories
- ProductGalleries
- Products
- Basket
- VideoGalleries
- Videos
- VideoTypes
